// Code generated by Wire protocol buffer compiler, do not edit.
// Source: squareup.protos.kotlin.oneof.OneOfMessage in one_of.proto
package com.squareup.wire.protos.kotlin

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.OneOf
import com.squareup.wire.OneOfProtoAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_2
import com.squareup.wire.internal.countNonNull
import com.squareup.wire.internal.sanitize
import com.squareup.wire.protos.kotlin.OneOfMessage.ChoiceOneOf.CHOICE_BAR
import com.squareup.wire.protos.kotlin.OneOfMessage.ChoiceOneOf.CHOICE_BAZ
import com.squareup.wire.protos.kotlin.OneOfMessage.ChoiceOneOf.CHOICE_FOO
import okio.ByteString
import kotlin.jvm.JvmField

/**
 * It's a one of message.
 */
public class OneOfMessage(
  choice: OneOf<Any>? = null,
  unknownFields: ByteString = ByteString.EMPTY
) : Message<OneOfMessage, Nothing>(ADAPTER, unknownFields) {
  val choice: OneOf<Any>? = run {
    if (choice == null) return@run null
    if (choice.key !in listOf(CHOICE_FOO,CHOICE_BAR,CHOICE_BAZ)) {
      throw IllegalArgumentException("Key isn't in the expected scope something.")
    }
    return@run choice
  }

  object ChoiceOneOf {
    val CHOICE_FOO = OneOf.Key(tag = 1, adapter = ProtoAdapter.INT32, generatedName = "foo")
    val CHOICE_BAR = OneOf.Key(tag = 3, adapter = ProtoAdapter.STRING, generatedName = "bar")
    val CHOICE_BAZ = OneOf.Key(tag = 4, adapter = ProtoAdapter.STRING, generatedName = "baz")
  }

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  public override fun newBuilder(): Nothing = throw AssertionError()

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is OneOfMessage) return false
    if (unknownFields != other.unknownFields) return false
    if (choice != other.choice) return false
    return true
  }

  public override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + choice.hashCode()
      super.hashCode = result
    }
    return result
  }

  public override fun toString(): String {
    val result = mutableListOf<String>()
    // TODO(Benoit) Delegate to something.
    if (choice != null) ProtoAdapter.ONE_OF.toString(choice)
    return result.joinToString(prefix = "OneOfMessage{", separator = ", ", postfix = "}")
  }

  public fun copy(
    choice: OneOf<Any>? = this.choice,
    unknownFields: ByteString = this.unknownFields
  ): OneOfMessage = OneOfMessage(choice, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<OneOfMessage> = object : ProtoAdapter<OneOfMessage>(
      FieldEncoding.LENGTH_DELIMITED,
      OneOfMessage::class,
      "type.googleapis.com/squareup.protos.kotlin.oneof.OneOfMessage",
      PROTO_2,
      null
    ) {
      public override fun encodedSize(value: OneOfMessage): Int {
        var size = value.unknownFields.size
        if (value.choice != null) {
          size += ProtoAdapter.ONE_OF.encodedSizeWithTag(value.choice)
        }
        return size
      }

      public override fun encode(writer: ProtoWriter, value: OneOfMessage): Unit {
        if (value.choice != null) {
          ProtoAdapter.ONE_OF.encodeWithTag(writer, value.choice)
        }
        writer.writeBytes(value.unknownFields)
      }

      public override fun decode(reader: ProtoReader): OneOfMessage {
        var foo: Int? = null
        var bar: String? = null
        var baz: String? = null
        // TODO(Benoit) How would we delegate that without consuming the reader?
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> foo = ProtoAdapter.INT32.decode(reader)
            3 -> bar = ProtoAdapter.STRING.decode(reader)
            4 -> baz = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        require(countNonNull(foo, bar, baz) <= 1) {
          "At most one of foo, bar, baz may be non-null"
        }
        val choice: OneOf<Any>? = when {
          foo != null -> OneOf(ChoiceOneOf.CHOICE_FOO, foo!!) as OneOf<Any>
          bar != null -> OneOf(ChoiceOneOf.CHOICE_BAR, bar!!) as OneOf<Any>
          baz != null -> OneOf(ChoiceOneOf.CHOICE_BAZ, baz!!) as OneOf<Any>
          else -> null
        }
        return OneOfMessage(
          choice = choice,
          unknownFields = unknownFields
        )
      }

      public override fun redact(value: OneOfMessage): OneOfMessage = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
